# Generated by Django 5.1.4 on 2024-12-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
    ]
